trigger:
- main


parameters:
  - name: kvConnectedServiceName
    default: 'azurerm-sandbox'
  - name: environment_components
    type: object
    default:
      - service_connection: aks-test
        department: cft
        aks:
          subscription: Pay-As-You-Go
          resource_group: rg-mycluster
          name: mycluster
    
pool:
  vmImage: 'ubuntu-latest'


steps:
- pwsh: |
    Get-ChildItem $(System.DefaultWorkingDirectory) -Recurse
  name: DebugCheckout
  displayName: Debug script checkout

- task: CmdLine@2
  displayName: 'Install Pluto' # update Pluto version if needed in wget and tar command
  inputs:
    script: |
      sudo apt-get update
      echo Downloading Pluto...
      wget github.com/FairwindsOps/pluto/releases/download/v5.10.1/pluto_5.10.1_linux_amd64.tar.gz
      tar xzvf pluto_5.10.1_linux_amd64.tar.gz
      echo Pluto downloaded successfully!      

# - task: AzureCLI@2
#   displayName: 'run pluto commands on AKS Cluster'
#   inputs:
#     azureSubscription: 'aks-test'
#     scriptType: 'bash'
#     scriptPath: '$(System.DefaultWorkingDirectory)/api-deprecation/aks.sh'
    # arguments: '${{ parameters.environment_components.aks.subscription }} ${{ parameters.environment_components.aks.resource_group }} ${{ parameters.environment_components.aks.name }} ${{ parameters.environment_components.department }}'

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'GitHub Management'
    repositoryName: 'taherkhan30/api-deprecation'
    id: '$(System.PullRequest.PullRequestNumber)'
    comment: 'myComment test'